// [N, NW, NE, E, W, SW, SE, S]
export const BOARD_WIDTH        = 8; //prettier-ignore
export const BOARD_HEIGHT       = 8; //prettier-ignore
export const LEFT_EDGE          = [1, 9, 17, 25, 33, 41, 49, 57]; //prettier-ignore
export const RIGHT_EDGE         = [8, 16, 24, 32, 40, 48, 56, 64]; //prettier-ignore
export const BOTTOM_EDGE           = [1, 2, 3, 4, 5, 6, 7, 8]; //prettier-ignore
export const TOP_EDGE        = [57, 58, 59, 60, 61, 62, 63, 64]; //prettier-ignore
export const KNIGHT_MOVES       = [15, 6, 17, 10, -10, -17, -6, -15]; //prettier-ignore
export const BISHOP_MOVES       = [0, 7, 9, 0, 0, -9, -7, 0]; //prettier-ignore
export const ROOK_MOVES         = [8, 0, 0, 1, -1, 0, 0, -8]; //prettier-ignore
export const QUEEN_MOVES        = [8, 7, 9, 1, -1, -9, -7, -8]; //prettier-ignore
export const KING_MOVES         = [8, 7, 9, 1, -1, -9, -7, -8]; //prettier-ignore
export const PAWN_MOVES_WHITE   = [8, 7, 9, 0, 0, 0, 0, 0]; //prettier-ignore
export const PAWN_MOVES_BLACK   = [0, 0, 0, 0, 0, -7, -9, -8]; //prettier-ignore
export const NORTH              = 0; //prettier-ignore
export const NORTH_WEST         = 1; //prettier-ignore
export const NORTH_EAST         = 2; //prettier-ignore
export const EAST               = 3; //prettier-ignore
export const WEST               = 4; //prettier-ignore
export const SOUTH_WEST         = 5; //prettier-ignore
export const SOUTH_EAST         = 6; //prettier-ignore
export const SOUTH              = 7; //prettier-ignore
